SELECT
  id,
  gmt_create,
  gmt_modified,
  seller_id,
  owner_id,
  subscription_id,
  delivery_custom_id,
  delivery_option,
  destination,
  custom_type,
  unit_type,
  discount,
  status,
  features,
  site_id,
  unique_code,
  ds
 FROM aer_ods_sg.s_seller_shipping_custom_v
