CREATE TABLE IF NOT EXISTS temp_adm_sellers
(
    seller_admin_seq                   BIGINT COMMENT 'seller_admin_seq',
    seller_admin_id                    STRING COMMENT 'seller_admin_id',
    business_model                     STRING COMMENT 'business_model',
    register_country_id                STRING COMMENT 'register_country_id',
    sub_accounts                       BIGINT COMMENT 'number of subaccount for admin account',
    merchant_type                      STRING COMMENT 'merchant_type',
    create_seller_time                 STRING COMMENT 'create_seller_time',
    store_id                           BIGINT COMMENT 'store_id',
    store_name                         STRING COMMENT 'store_name',
    store_link                         STRING COMMENT 'store_link',
    store_type                         STRING COMMENT 'store_type',
    havana_id                          STRING COMMENT 'havana_id',
    is_ka_ind                          STRING COMMENT 'is ka seller Y/N',
    first_public_item_time             STRING COMMENT 'first_public_item_time',
    first_pay_order_time               STRING COMMENT 'first_pay_order_time',
    funnel_status                      STRING COMMENT 'funnel_status',
    online_itm_cnt                     BIGINT COMMENT 'online_itm_cnt',
    in_stock_itm_cnt                   BIGINT COMMENT 'in_stock_itm_cnt',
    offline_itm_cnt                    BIGINT COMMENT 'offline_itm_cnt',
    all_finished_pord                  BIGINT COMMENT 'all_finished_pord',
    all_finished_gmv_rub               DOUBLE COMMENT 'all_finished_gmv_rub',
    all_finished_gmv_usd               DOUBLE COMMENT 'all_finished_gmv_usd',
    all_finished_item_commission_rub   DOUBLE COMMENT 'all_finished_item_commission_rub',
    all_finished_market_commission_rub DOUBLE COMMENT 'all_finished_market_commission_rub',
    all_finished_log_commission_rub    DOUBLE COMMENT 'all_finished_log_commission_rub',
    all_finished_item_commission_usd   DOUBLE COMMENT 'all_finished_item_commission_usd',
    all_finished_market_commission_usd DOUBLE COMMENT 'all_finished_market_commission_usd',
    all_finished_log_commission_usd    DOUBLE COMMENT 'all_finished_log_commission_usd',
    date_r6                            STRING COMMENT 'date_r6',
    date_s0                            STRING COMMENT 'date_s0',
    date_s1                            STRING COMMENT 'date_s1',
    date_s2                            STRING COMMENT 'date_s2',
    date_s3                            STRING COMMENT 'date_s3',
    itm_cate_lv1_desc                  STRING COMMENT 'itm_cate_lv1_desc',
    itm_cate_lv1_id                    STRING COMMENT 'itm_cate_lv1_id',
    gmv_cate_lv1_desc                  STRING COMMENT 'gmv_cate_lv1_desc',
    gmv_cate_lv1_id                    STRING COMMENT 'gmv_cate_lv1_id',
    login_days_7d                      BIGINT COMMENT 'login_days_7d',
    login_days_30d                     BIGINT COMMENT 'login_days_30d',
    login_days_90d                     BIGINT COMMENT 'login_days_90d',
    login_days_180d                    BIGINT COMMENT 'login_days_180d',
    itm_change_days_7d                 BIGINT COMMENT 'itm_change_days_7d',
    itm_change_days_30d                BIGINT COMMENT 'itm_change_days_30d',
    itm_change_days_90d                BIGINT COMMENT 'itm_change_days_90d',
    itm_change_days_180d               BIGINT COMMENT 'itm_change_days_180d',
    send_days_7d                       BIGINT COMMENT 'send_days_7d',
    send_days_30d                      BIGINT COMMENT 'send_days_30d',
    send_days_90d                      BIGINT COMMENT 'send_days_90d',
    send_days_180d                     BIGINT COMMENT 'send_days_180d',
    api_days_7d                        BIGINT COMMENT 'api_days_7d',
    api_days_30d                       BIGINT COMMENT 'api_days_30d',
    api_days_90d                       BIGINT COMMENT 'api_days_90d',
    api_days_1800d                     BIGINT COMMENT 'api_days_180d',
    trd_pay_gmv_rub_7d                 DOUBLE COMMENT 'trd_pay_gmv_rub_7d',
    trd_pay_gmv_rub_30d                DOUBLE COMMENT 'trd_pay_gmv_rub_30d',
    trd_pay_gmv_rub_90d                DOUBLE COMMENT 'trd_pay_gmv_rub_90d',
    trd_pay_gmv_rub_180d               DOUBLE COMMENT 'trd_pay_gmv_rub_180d',
    trd_pay_gmv_rub_365d               DOUBLE COMMENT 'trd_pay_gmv_rub_365d',
    trd_pay_gmv_rub_ttl                DOUBLE COMMENT 'trd_pay_gmv_rub_ttl',
    trd_pay_gmv_usd_7d                 DOUBLE COMMENT 'trd_pay_gmv_usd_7d',
    trd_pay_gmv_usd_30d                DOUBLE COMMENT 'trd_pay_gmv_usd_30d',
    trd_pay_gmv_usd_90d                DOUBLE COMMENT 'trd_pay_gmv_usd_90d',
    trd_pay_gmv_usd_180d               DOUBLE COMMENT 'trd_pay_gmv_usd_180d',
    trd_pay_gmv_usd_365d               DOUBLE COMMENT 'trd_pay_gmv_usd_365d',
    trd_pay_gmv_usd_ttl                DOUBLE COMMENT 'trd_pay_gmv_usd_ttl',
    trd_pay_pord_7d                    BIGINT COMMENT 'trd_pay_pord_7d',
    trd_pay_pord_30d                   BIGINT COMMENT 'trd_pay_pord_30d',
    trd_pay_pord_90d                   BIGINT COMMENT 'trd_pay_pord_90d',
    trd_pay_pord_180d                  BIGINT COMMENT 'trd_pay_pord_180d',
    trd_pay_pord_365d                  BIGINT COMMENT 'trd_pay_pord_365d',
    trd_pay_pord_ttl                   BIGINT COMMENT 'trd_pay_pord_ttl',
    trd_pay_items_7d                   BIGINT COMMENT 'trd_pay_items_7d',
    trd_pay_items_30d                  BIGINT COMMENT 'trd_pay_items_30d',
    trd_pay_items_90d                  BIGINT COMMENT 'trd_pay_items_90d',
    trd_pay_items_180d                 BIGINT COMMENT 'trd_pay_items_180d',
    trd_pay_items_365d                 BIGINT COMMENT 'trd_pay_items_365d',
    online_items_7d                    BIGINT COMMENT 'online_items_7d',
    online_items_30d                   BIGINT COMMENT 'online_items_7d',
    online_items_90d                   BIGINT COMMENT 'online_items_7d',
    online_items_180d                  BIGINT COMMENT 'online_items_7d',
    online_items_365d                  BIGINT COMMENT 'online_items_7d',
    exposure_7d                        BIGINT COMMENT 'exposure_7d',
    exposure_30d                       BIGINT COMMENT 'exposure_30d',
    ipv_7d                             BIGINT COMMENT 'ipv_7d',
    ipv_30d                            BIGINT COMMENT 'ipv_30d',
    exposure_mbr_uv_7d                 BIGINT COMMENT 'exposure_mbr_uv_7d',
    exposure_mbr_uv_30d                BIGINT COMMENT 'exposure_mbr_uv_30d',
    ipv_mbr_uv_7d                      BIGINT COMMENT 'ipv_mbr_uv_7d',
    ipv_mbr_uv_30d                     BIGINT COMMENT 'ipv_mbr_uv_30d',
    buynow_7d                          BIGINT COMMENT 'buynow_7d',
    buynow_30d                         BIGINT COMMENT 'buynow_30d',
    addwishlist_7d                     BIGINT COMMENT 'addwishlist_7d',
    addwishlist_30d                    BIGINT COMMENT 'addwishlist_30d',
    addcart_7d                         BIGINT COMMENT 'addcart_7d',
    addcart_30d                        BIGINT COMMENT 'addcart_30d',
    date_slr_offline                   STRING COMMENT 'date_slr_offline',
    item_qty_before_offline            BIGINT COMMENT 'item_qty_before_offline',
    trd_pay_before_offline_gmv_rub_30d DOUBLE COMMENT 'trd_pay_before_offline_gmv_rub_30d',
    trd_pay_before_offline_gmv_usd_30d DOUBLE COMMENT 'trd_pay_before_offline_gmv_usd_30d',
    trd_pay_before_offline_pord_30d    BIGINT COMMENT 'trd_pay_before_offline_pord_30d',
    is_churn                           STRING COMMENT 'is churn seller (14d after offline) Y/N',
    slr_total_price_index              DOUBLE COMMENT 'seller price index based on items matched with competitors',
    itm_match_price_index              BIGINT COMMENT 'number of matched items for calculation seller price index',
    itm_ozon                           BIGINT COMMENT 'number of items in ozon',
    itm_wb                             BIGINT COMMENT 'number of items in wb',
    rating_avg_180d                    DOUBLE COMMENT 'share positive evaluations for last 180d',
    avg_desc_eval_180d                 DOUBLE COMMENT 'average item describe evaluation for last 180d',
    avg_service_eval_180d              DOUBLE COMMENT 'average seller service evaluation for last 180d',
    avg_shipping_eval_180d             DOUBLE COMMENT 'average shipping evaluation for last 180d',
    is_affiliate                       STRING COMMENT 'is now affiliate seller Y/N',
    is_local_manually_blocked          STRING COMMENT 'is_local_manually_blocked Y/N',
    local_block_type                   STRING COMMENT 'local_block_type',
    local_block_time                   STRING COMMENT 'local_block_time',
    local_unblock_time                 STRING COMMENT 'local_unblock_time',
    cnt_ord_s_and_ns_7d                BIGINT COMMENT 'number pord send and not send for last 7d',
    cnt_ord_s_and_ns_30d               BIGINT COMMENT 'number pord send and not send for last 30d',
    cnt_ord_s_and_ns_90d               BIGINT COMMENT 'number pord send and not send for last 90d',
    cnt_ord_s_and_ns_180d              BIGINT COMMENT 'number pord send and not send for last 180d',
    cnt_ord_s_and_ns_365d              BIGINT COMMENT 'number pord send and not send for last 365d',
    cnt_ord_s_and_ns_ttl               BIGINT COMMENT 'number pord send and not send for all period',
    cnt_ord_ns_7d                      BIGINT COMMENT 'number pord not send for last 7d',
    cnt_ord_ns_30d                     BIGINT COMMENT 'number pord not send for last 30d',
    cnt_ord_ns_90d                     BIGINT COMMENT 'number pord not send for last 90d',
    cnt_ord_ns_180d                    BIGINT COMMENT 'number pord not send for last 180d',
    cnt_ord_ns_365d                    BIGINT COMMENT 'number pord not send for last 365d',
    cnt_ord_ns_ttl                     BIGINT COMMENT 'number pord not send for all period',
    main_log_model_orders              STRING COMMENT 'main_log_model_orders',
    main_provider_orders               STRING COMMENT 'main_provider_orders',
    main_log_model_items               STRING COMMENT 'main_log_model_orders for items online/all',
    main_provider_items                STRING COMMENT 'main_provider_orders for items online/all',
    ds                                 STRING COMMENT 'partition'
)